apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cronjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronjob
  template:
    metadata:
      labels:
        app: cronjob
    spec:      
      containers:
      - image: nebulaepyxis/cronjob.backend.cronjob:1.0.12
        name: cronjob
        volumeMounts:
        - name: google-application-credentials
          mountPath: "/etc/GOOGLE_APPLICATION_CREDENTIALS"
          readOnly: true
        resources:
          requests:
            cpu: "50m"
        env:     
        # EVENT STORE CONFIG 
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/GOOGLE_APPLICATION_CREDENTIALS/gcloud-service-key.json  
        - name: EVENT_STORE_BROKER_TYPE
          value: PUBSUB
        - name: EVENT_STORE_BROKER_EVENTS_TOPIC
          value: events
        - name: EVENT_STORE_STORE_TYPE
          value: MONGO
        - name: EVENT_STORE_STORE_URL
          value: mongodb://dbevents-0.dbevents:27017,dbevents-1.dbevents:27017,dbevents-2.dbevents:27017/test?replicaSet=rs0
        - name: EVENT_STORE_STORE_AGGREGATES_DB_NAME
          value: Aggregates
        - name: EVENT_STORE_STORE_EVENTSTORE_DB_NAME
          value: EventStore
        # INTERNAL MONGO DB CONFIG
        - name: MONGODB_URL
          value: mongodb://cronjob-mongo:27017
        - name: MONGODB_DB_NAME
          value: Cronjob
        # JWT CONGIF        
        - name: JWT_PUBLIC_KEY
          value: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsQBquKLlhsh1IObDD+KP45iBjelCjiF4mxLEqFkwHpGBZZckjQRPeXCc/z/nhJd47VnmyFiRFNGifpIraneLJYz1XrJ6B1fqGyfLf4mFErIffk4lQpCVUeaW/QyMFdwHN2jhe3S7yWx3gaD3ZKOX7egqZhD5gTEaYldhJX26kmJJHvuuG8t/etjxeNLy0GhLi2E1WhP6M9NGtVKS/02P16CJPr0SFQVXOUdgi5kQUS74rHB/CzEjQNziO2v2BnZVDMbKckSpzWl/zcu388/81hIlLvYpO+NtseioIQYB9sHBoaEs2cKwNEUEGKzcDezfR8fdSoGJ2wYQBnhQTMH0ewIDAQAB\n-----END PUBLIC KEY-----
        # API - GATEWAY CONFIG
        - name: GATEWAY_REPLIES_TOPIC_SUBSCRIPTION
          value: emi-gateway-replies-topic-mbe-cronjob
        - name: REPLY_TIMEOUT
          value: '2000'
        - name: BROKER_TYPE
          value: PUBSUB
        # RESET LOCK INITIALIZE BACKED
        - name: LOCKVERSION
          value: "cries in despair"
        
      volumes:
      - name: google-application-credentials
        secret:
          secretName: google-application-credentials      